doubtfire-lms/doubtfire-web

src/app/common/partials/directives/grade-icon.coffee
src/app/common/services/task-service.coffee
src/app/tasks/partials/directives/grade-task-modal.coffee
src/app/tasks/partials/directives/provide-task-feedback.coffee
src/app/tasks/partials/directives/task-feedback-directive.coffee
src/app/tasks/partials/directives/task-modals.coffee
src/app/tasks/partials/templates/grade-task-modal.tpl.html
src/app/tasks/partials/templates/task-admin.tpl.html
src/app/tasks/partials/templates/task-feedback.tpl.html
src/less/common.less
src/less/modules/task-feedback.less

This pull request adds graded task functionality to the app.
- Tasks can now be marked as graded tasks in the unit's task admin panel.
- Tasks that are marked by tutors in either a `complete`, `discuss` or `demonstrate` state for tasks that are graded tasks will be prompted by tutors select the desired grade for that task
- Graded task feedback is displayed underneath the task status in the task feedback panel

Add graded tasks to feedback and admin

---

src/app/tasks/partials/templates/task-admin.tpl.html
src/app/units/partials/templates/unit-admin-context.tpl.html

The calendar fields were too large and the icon for the calendar picker was too far away from the actual date in the field.
Resolves [trello card](https://trello.com/c/YvTgcoac/54-issue-7-calendar-icon-is-too-far-across-from-the-date-text) issue

Reduce calendar field width

---

src/app/tasks/task-viewer/task-viewer.scss
src/app/tasks/task-viewer/task-viewer.tpl.html

Added Grade Icon next to the title of the task. See more details on Trello card: https://trello.com/c/5cVfPtyU/39-add-grade-details-to-task-sheet-so-that-students-can-see-which-grade-a-task-relates-to-if-it-is-not-apparent-from-the-name-abbre

LOOKS: Added Grade Icon next to Task Viewer title

---

src/app/common/alert-list/alert-list.coffee
src/app/common/alert-list/alert-list.tpl.html
src/app/common/common.coffee
src/index.html

Stop H4 "alert.type | ucfirst" from displaying in index.html when loading

FIX: Remove text appearing on index when loading

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.coffee

Logic for selected task still relied on deprecated `task.id` which should NEVER be referenced!

Use project_id and task_def_id for selected task

---

src/app/common/services/task-service.coffee

This PR will remove periods from task IDs which causes an error, as no period characters can be present in querySelector IDs.

FIX: Remove periods for querySelector ids

---

src/styles/mixins/task-list.scss

This PR fixes a visual bug in the inbox task list.
Currently, the use of border-right in the task-inbox introduced margin errors because of how border heights are computed:
After refactoring to use box shadows:

LOOKS: Fix border-right visual bug

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.coffee

This will make sure that a convenor can log in and view their task submissions based upon their own tutorials, if they have any. The same applies to tutors. Prior to this enhancement, a convenor would always be directed to a task inbox list that reflects all submissions from all tutorials, not just their own.

ENHANCE: Update task list inbox based on user tutorials

---

src/app/api/models/portfolion-submission.coffee
src/app/api/models/task-feedback.coffee
src/app/common/pdf-panel-viewer/pdf-panel-viewer.coffee
src/app/common/pdf-panel-viewer/pdf-panel-viewer.scss
src/app/common/pdf-panel-viewer/pdf-panel-viewer.tpl.html
src/app/common/pdf-viewer/pdf-viewer.coffee
src/app/common/pdf-viewer/pdf-viewer.scss
src/app/common/pdf-viewer/pdf-viewer.tpl.html
src/app/common/services/unit-service.coffee
src/app/projects/states/dashboard/dashboard.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-submission-card/task-submission-card.coffee
src/app/projects/states/dashboard/directives/task-dashboard/task-dashboard.coffee
src/app/projects/states/dashboard/directives/task-dashboard/task-dashboard.tpl.html
src/app/projects/states/portfolio/directives/portfolio-review-step/portfolio-review-step.tpl.html
src/app/tasks/task-definition-editor/task-definition-editor.coffee

This PR resolves #81.
As shown in https://github.com/doubtfire-lms/doubtfire-api/pull/70, the `Content-Disposition` header must not be sent when rendering PDF in an `object` element for Chrome and Firefox.
This PR ensures the PDF viewer and PDF panel viewer both use the PDF viewer, using the `as_attachment` query proposed in https://github.com/doubtfire-lms/doubtfire-api/pull/70.

Resolve native PDF rendering using new as attachment parameter

---

src/app/common/markdown-editor/markdown-editor.scss
src/app/common/markdown-editor/markdown-editor.tpl.html

This PR will create a small panel underneath the comment window, so that icons do not overlap the text window. This will also provide a space for upcoming audio comment feature.

LOOKS: Move comment icons underneath text field

---

src/app/common/filters/filters.coffee
src/app/common/services/project-service.coffee
src/app/common/services/unit-service.coffee
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.coffee

If I am a tutor and I have a group assigned to me, I should see all students from _any_ individual tutorial (i.e., not just my students in my tutorial).
E.g., Eda, Kattie and Michael are in a group. Eda is in Tutorial A, Katie is in Tutorial B, and Michael is in Tutorial C. I am a tutor for Tutorial C and a tutor for this group. I should therefore see Eda and Katie as well.
This PR resolves this issue, as previously I couldn’t see the other students.

Resolves issues with Marking by Task Definition.

---

src/app/projects/states/dashboard/directives/task-dashboard/directives/task-description-card/task-description-card.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-status-card/task-status-card.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-submission-card/task-submission-card.tpl.html

This PR ensures that all task actions are pull-left, as apposed to the current state where most are pull-left but the recently added action button was pull-right. It also removes double icons from the action buttons.

Looks: Improve download button consistency

---

src/app/tasks/task-comment-composer/task-comment-composer.coffee

This PR will ensure that when the enter key is pressed while the comment field is not empty, it won't add the new line (as the previous behavior), but also will not attempt to add the comment. This will ensure an error message won't appear

ENHANCE: Don't attempt send comment if text is empty

---

src/app/api/models/task-definition.coffee
src/app/tasks/task-definition-editor/task-definition-editor.coffee
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.coffee
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.tpl.html

This PR will allow staff to download all task submissions as a zip file for a task definition on the task definition marking view. It also fixes a bug with the "all task submission" entry being shown inappropriately on the task definition marking view, and not the inbox view.

New: add submission zip export

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.coffee

This PR will ensure that when visiting the task inbox, it will not automatically select the first task in the inbox. If the URL contains a task it will select it automatically as before. The purpose of this change is to ensure not accidentally reading comments in the first task.

ENHANCE: Do not select first task in inbox if visiting inbox

---

src/app/tasks/task-comment-composer/task-comment-composer.tpl.html

This PR will ensure only plaintext will be allowed in the comment text editor. Previously, pasting style-rich text into the editor would render the styles. For example:
Would now be: 
This can be merged safely at any time 👍

FIX: Only allow plaintext in the comment editor

---

src/app/common/services/project-service.coffee
src/app/common/services/task-service.coffee
src/app/common/services/unit-service.coffee
src/app/projects/states/dashboard/directives/student-task-list/student-task-list.coffee
src/app/projects/states/dashboard/directives/student-task-list/student-task-list.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-status-card/task-status-card.tpl.html

By default, student task inbox is sorted according to the sequence number. (1.1, 1.2....).
The changes in this PR includes sorting the student task inbox according to the priority.
1. If the student has missed the target date of few tasks then those tasks will appear on the top of the inbox. All the tasks will be sorted according to the priority. Pass tasks are more important than credit so the pass tasks will appear on the top irrespective of the due date. So, if a pass task was due yesterday and a credit task was due 1 week ago then also pass task will be on the top of the inbox.
2. If there are no overdue tasks then tasks will be sorted according to the due date. So if a distinction task is due in 5 days and pass task is due in 2 weeks then the distinction task will be shown on top. If …

ENHANCE: Sort student task inbox by task priority

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.coffee

Initially when the tutor opens the task box the first task is selected automatically. If the tutor adds some filters then the task still remains selected even if it is not in the filtered list. This PR fixes this bug. It will deselect the task if it is not in the new filtered list and automatically select the first task in the new list. If after applying the filter the task is still in the new filtered list then it will remain selected.

FIX: fix default selected task for tutors

---

src/app/common/services/project-service.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-due-card/task-due-card.tpl.html

Fixed the dates and weeks shown in the task-cards. If the number of days is less than 14 then it will be shown as days else it will be shown in weeks.

FIX: Replace weeks with days

---

src/app/tasks/task-comment-composer/task-comment-composer.component.ts
src/app/tasks/task-comment-composer/task-comment-composer.html

Contenteditable does not support "plaintext-only" property value on non-webkit browsers, this PR ensures the value is set to true on non-webkit browsers to ensure they can use the contenteditable div.

FIX: Add support for Firefox with contenteditable

---

src/app/common/services/project-service.coffee
src/app/common/services/task-service.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-status-card/task-status-card.coffee

Auto trigger does not check for existing extension requests, and we should generally make the user responsible for this.

ENHANCE: Remove automatic trigger of extension in favour of alert warning

---

README.md
setup.sh

This PR seeks to merge updates to the Doubtfire-web installation in Ubuntu. Specifically, it creates an installation script, and updates the corresponding information in the readme.md.
The installation process described in the updated documentation has been tested from scratch, resulting in a functional instance of Doubtfire-web. Similarly, the ./setup.sh script has been tested from scratch (n.b. only using Ubuntu 18.04 LTS), also resulting in a functional instance of Doubtfire-web.
If you have any questions, please contact @macite or @jakerenzella.

Doubtfire-web Installation Updates

---

src/app/units/states/edit/directives/unit-staff-editor/unit-staff-editor.coffee
src/app/units/states/edit/directives/unit-staff-editor/unit-staff-editor.tpl.html

Enable the selection of main convenor for a unit from a unit's staff list. Note that only one staff member may a convenor.
If we want to include the user icon in the drop down when adding new staff to a unit, the unit serialiser will need to be extended to include each staff member's email in the unit's staff list.

FEATURE: Specify main convenor

---

src/app/admin/states/activities/activity-type-list/activity-type-list.component.html
src/app/admin/states/activities/activity-type-list/activity-type-list.component.ts
src/app/admin/states/campuses/campus-list/campus-list.component.html
src/app/admin/states/campuses/campus-list/campus-list.component.ts
src/app/common/entity-form/entity-form.component.ts
src/app/units/states/edit/directives/unit-tutorials-list/unit-tutorials-list.component.html
src/app/units/states/edit/directives/unit-tutorials-list/unit-tutorials-list.component.ts

Implement sorting functionality on the `EntityForm`. This was required because Angular's `mat-sort-header` can't sort values that are objects, so you need to define how those values are compared in order to sort.

FIX: Entity Form Sorting

---

src/app/common/services/unit-service.coffee
src/app/tasks/task-definition-editor/task-definition-editor.coffee
src/app/tasks/task-definition-editor/task-definition-editor.tpl.html
src/app/units/states/edit/directives/unit-tasks-editor/unit-tasks-editor.tpl.html

Note that the below  changes are only operational within units that have at least one stream
Add a stream column to the Unit Task List:
When editing task, enable the ability to specify which stream the task belongs to:

NEW: Specify stream for unit tasks

---

src/app/units/states/edit/directives/unit-ilo-editor/unit-ilo-editor.tpl.html

Responsive design for intended learning outcome editor page. The screenshots of changed and existing view is attached below. The overflow flaw has been fixed and now has scroll.

Update Unit Intended Learning outcome Editor Page

---

src/app/projects/states/portfolio/directives/portfolio-grade-select-step/portfolio-grade-select-step.coffee
src/app/projects/states/portfolio/directives/portfolio-grade-select-step/portfolio-grade-select-step.tpl.html
src/app/units/states/portfolios/portfolios.tpl.html

This PR ensures the portfolio grade select buttons correctly change the submitted grade, rather than the target grade. It also updates the portfolio assessment table to include the new submitted grade. 
Please refer to doubtfire-api PR for further information: [NEW: Add submitted grade to portfolio submission](https://github.com/doubtfire-lms/doubtfire-api/pull/285)
- Test that the "submitted_grade" value is modified when selecting the grade select buttons when submitting the portfolio.
- Test that a student cannot change the submitted grade after portfolio has been submitted (through an API request)

NEW: Add submitted grade to portfolio submission

---

src/app/common/modals/calendar-modal/calendar-modal.component.ts

Slight extension to https://github.com/doubtfire-lms/doubtfire-web/pull/293 that lists only active units for exclusion, i.e. only units that are listed on the home page, under "Units You Study".

ENHANCE: List only _active_ units for calendar exclusion

---

src/styles/common/typeface.scss

Fixes the issue where material icons would be loaded as Roboto before initialised. 
Run on all browsers locally.

FIX: Ensure material icons style overrides Roboto in typography file

---

src/app/tasks/task-comments-viewer/intelligent-discussion-player/intelligent-discussion-player.component.ts
src/tsconfig.app.json

The DiscussionComment used to be an interface on the discussion-player component, however, with the new DIscussionComment class, it should not be used to ensure the type definition reflects the actual properties of the class. Also includes a small change to include all ts files in the tsconfig

FIX: Remove redundant DiscussionComment interface

---

src/app/common/header/header.coffee
src/app/common/header/header.tpl.html
src/app/doubtfire-angular.module.ts
src/app/doubtfire-angularjs.module.ts
src/app/sessions/service-worker-updater/check-for-update.service.ts
src/manifest.webmanifest

Adds an update check service which occasionally prompts the service worker to check for updates of source files on the server, and refreshes if updates are found. Also adds a button to force check for updates. Currently configured to every 4 hours.
This can't be tested locally, so needs to be tested on staging

New: Add service worker forced refresh

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.html

This PR disables the staff task inbox from coaching the list as it uses dynamic components.

fix: disable chaching in staff task list

---

README.md

Remove prompt signs in commands and provide better syntax highlight on `README.md`

docs: remove prompt signs and add syntax highlight

---

src/app/visualisations/progress-burndown-chart.coffee

Change in src/app/visualizations/progress-burndown-chart.coffee
Convert visualized Unix Timestamp to human readable format.

Fix a Bug - covert Unix Timestamp

---

src/app/units/states/edit/directives/unit-tasks-editor/unit-tasks-editor.tpl.html

Fixes # (issue)
The data for stream and group is not align in task admin page.
The origin HTML lable and data are not align
Before: 
After: 
Tested both have label group set and have not group set.

fix: fix the data for group and stream not align
