doubtfire-lms/doubtfire-web

src/app/projects/partials/templates/view-comments.tpl.html

Change comment send icon from the plus icon to the send icon.

Change comment send icon

---

src/app/common/services/task-service.coffee
src/app/tasks/task-comments-viewer/task-comments-viewer.coffee
src/app/tasks/task-feedback-assessor/task-feedback-assessor.coffee
src/app/tasks/task-feedback-assessor/task-feedback-assessor.tpl.html

When a comment status is applied, and there is an unsent comment in the
text field, the comment will now be sent.

ENHANCE: Send comment on assessor

---

src/app/tasks/task-viewer/task-viewer.tpl.html
src/styles/common/overrides/nav-tabs-overrides.scss

Now on the task viewer, there is an indicator to show how many comments have been left on a single task.

Comments count

---

src/app/common/services/unit-service.coffee
src/app/units/unit-student-list/unit-student-list.coffee
src/app/units/unit-students-editor/unit-students-editor.coffee
src/app/units/unit-students-editor/unit-students-editor.tpl.html

As is the case with the tutor student list where a tutor can update a student tutorial, a convenor may now update a student tutorial

EHANCE: Student tutorial can now be changed in convenor view

---

src/app/common/services/task-service.coffee
src/app/tasks/task-feedback-assessor-list/task-feedback-assessor-list.tpl.html

Tasks within the feedback view now display both the last submission date for the task and the number of times the task has been submitted

EHNACE: Add times submitted and last submission date to task

---

src/app/projects/project-progress-dashboard/project-progress-dashboard.tpl.html

Thanks to Kai for noticing the typo :)

FIX: Fix typo in Target Grade tpl

---

src/app/projects/project-portfolio-wizard/portfolio-review-step/portfolio-review-step.tpl.html

"Yeah, I'll just go remove this file0. ...wait what." That was bugging me for a while.

FIX: Pluralisation typo

---

src/app/home/states/home/home.coffee
src/app/home/states/home/home.scss
src/app/home/states/home/home.tpl.html

Adds a spinner to homepage for when API is still spinning up

Add spinner to homepage

---

src/app/projects/states/dashboard/directives/progress-dashboard/progress-dashboard.coffee
src/app/projects/states/dashboard/directives/progress-dashboard/progress-dashboard.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/task-dashboard.coffee
src/app/projects/states/dashboard/directives/task-dashboard/task-dashboard.tpl.html

Add the student's name to their dashboard and each submission when being viewed by a tutor

ENHANCE: Add student name to project dashboard when viewed by tutor

---

src/app/common/header/header.tpl.html
src/app/units/states/tasks/feedback/feedback.coffee

This PR Will:
* Rename "Give Student Feedback" to "In-Class Feedback"
* Fix title of  "Mark By Definition" to "Mark By Task Definition"

ENHANCE: Rename two tutor action titles in dropdown menu

---

src/app/common/services/recorder-service.coffee

- Remove large comment blocks
- Remove unused code

Audio Recorder Code-Quality Improvements

---

src/app/common/services/project-service.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-description-card/task-description-card.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-description-card/task-description-card.tpl.html

Changes to support start date on task descriptions - Pranit, Ben

NEW: Add start date on task description

---

src/app/tasks/task-ilo-alignment/task-ilo-alignment-editor/task-ilo-alignment-editor.tpl.html

There is some debugging code in the task alignment editor that this PR removes.

FIX: Remove debug code from task alignment editor

---

src/app/common/file-uploader/file-uploader.coffee

Allow gif upload now supported in back end

FIX: Enable gif file upload on submission

---

.dockerignore
Dockerfile
Gruntfile.js
src/assets/fonts/bootstrap
src/assets/fonts/font-awesome

This PR will support Docker on Windows.

Support Docker on Windows

---

src/app/common/user-icon/user-icon.coffee
src/app/home/states/new-user-wizard/new-user-wizard.coffee
src/app/home/states/new-user-wizard/new-user-wizard.tpl.html

Ensure the wizard allows staff to adjust notification settings, and loads when no projects.

FIX: Correct issues with new user wizard for staff

---

.dockerignore
Dockerfile
Gruntfile.js
package-lock.json
package.json
src/assets/fonts/bootstrap
src/assets/fonts/font-awesome

This PR will:
* Dockerize web project
* Enable live-reloading for both Angular 1 components and Angular 6 components
* with/without Docker
To describe merging strategy, I will add a comment to doubtfire-lms/doubtfire-api#121.

Dockerize (Angular 6 + 1)

---

package.json

This PR will update the package.json file to add the deployment. The previous commits have been rolled into other PRs

Update angular 7 migration for deployment

---

angular.json
package.json
src/app/common/modals/extension-modal/extension-modal.component.ts
src/app/common/services/project-service.coffee
src/app/common/services/task-service.coffee
src/app/common/services/unit-service.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-description-card/task-description-card.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-description-card/task-description-card.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-due-card/task-due-card.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-due-card/task-due-card.tpl.html
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-status-card/task-status-card.coffee
src/app/projects/states/dashboard/directives/task-dashboard/directives/task-status-card/task-status-card.tpl.html

Previously Time Exceeded only occurred after the deadline, now it happens after the due date. As a result we need to make sure they can request an extension when tasks are in the time exceeded state.

FIX: Ensure that students can request extensions on time exceeded

---

src/app/common/services/task-service.coffee
src/app/tasks/task-comment-composer/task-comment-composer.component.ts
src/app/tasks/task-comment-composer/task-comment-composer.html
src/app/tasks/task-comment-composer/task-comment-composer.scss
src/app/tasks/task-comments-viewer/task-comments-viewer.coffee
src/app/tasks/task-comments-viewer/task-comments-viewer.scss
src/app/tasks/task-comments-viewer/task-comments-viewer.tpl.html

Overall cleanup of task comment panel:
* Make comments more readable by moving delete icon into overflow menu (right click to access if permissible).
* Redesign the task comment composer to make it cleaner and easier to notice that it's an input field.
* Only show comment information if it is the last comment from that author, or the comments are more than 15 minutes apart
* Make comments more compact.
Works on Firefox.

NEW: Redesign task comments panel to fix various issues.

---

src/app/common/long-press/on-long-press.coffee
src/app/tasks/task-comment-composer/task-comment-composer.scss
src/app/tasks/task-comments-viewer/task-comments-viewer.tpl.html
src/app/visualisations/progress-burndown-chart.coffee
src/styles/common/global.scss

* Ensure task comment composer doesn't grow as the content of the input grows.
* Fix a potential bug which may cause tooltips or popovers to capture mouse.
* Remove the task comment tooltip, it shows no extra information now that we have timestamps/author information. It was previously causing screen flickering issues on certain browser's OSs due to how the contents of the tooltip were appended to the body.
* Fix some unreachable code **(this needs to be reviewed carefully)**

QUALITY: Various quality fixes.

---

src/app/visualisations/progress-burndown-chart.coffee

FIX: Remove clipping of x axis value for burndown.

---

src/app/common/services/task-service.coffee
src/app/tasks/task-comments-viewer/task-comments-viewer.scss
src/app/tasks/task-comments-viewer/task-comments-viewer.tpl.html

* Fixes a typo with discussion bubbles
* Fixes CSS for pdf comments.

LOOKS: Treat PDFs as a bubble

---

src/app/common/services/task-service.coffee
src/app/tasks/task-comments-viewer/task-comments-viewer.coffee
src/app/tasks/task-comments-viewer/task-comments-viewer.scss
src/app/tasks/task-comments-viewer/task-comments-viewer.tpl.html

Previously delete comments was triggered by a right click to open a menu on a comment. This was not discoverable, and this PR replaces the interaction with a delete icon to the right or left of an deletable comment.

Various comment improvements

---

src/app/doubtfire-angular.module.ts

Small fix to ensure service worker is always registered

FIX: Ensure serviceworker is registered immediately

---

ngsw-config.json
package-lock.json
package.json
src/manifest.webmanifest

Web manifest changes

---

src/app/ajs-upgraded-providers.ts
src/app/common/modals/comments-modal/comments-modal.coffee
src/app/doubtfire-angular.module.ts

Fix the comment image modal not working.
Addresses issue https://github.com/doubtfire-lms/doubtfire-web/issues/257

FIX: Refactor comment modal to use new comment provider

---

src/app/units/states/edit/directives/unit-students-editor/unit-students-editor.component.ts

The student list was very slow with large student lists. This change improves the efficiency and ensures lazy loading is active.

Fix ordering of datasource to ensure fast loading in large datasets

---

package-lock.json
package.json
src/app/common/services/emoji.service.ts

Ensure compound emoji (emoji which are comprised of multiple emoji in sequence) are supported.

Fix compound emoji

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.html
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.ts

Adds task pin menu and method for task inbox

NEW: Add pin menu to task inbox overflow

---

src/app/common/services/project-service.coffee
src/app/projects/states/dashboard/directives/student-task-list/task-list-item/task-list-item.component.html
src/styles/mixins/task-list.scss

This PR adds the following tooltips to the task list,
- Individual/group task
- Start/complete task in _X_ days
- Task overdue
- _X_ new comments (superscript)
- Plagiarism detected (superscript)

ENHANCE: Tooltips for the Task List

---

src/app/admin/states/users/users.tpl.html
src/styles/common/extensions/panel-footer-toolbar.scss

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
If you have any questions, please contact @macite or @jakerenzella.

Made user administration view to responsive.

---

src/app/admin/states/units/units.tpl.html

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
If you have any questions, please contact @macite or @jakerenzella.

Made the Manage unit page responsive.

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.html
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.ts

Quick PR to hide inbox overflow until pin feature is merged in backend

QUALITY: Hide task inbox overflow until pin ready

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.scss

Fixes an issue in inbox with long names

LOOKS: Fix truncation issue with long names

---

src/app/common/entity-form/entity-form.component.ts
src/app/units/states/edit/directives/unit-tutorials-list/unit-tutorials-list.component.ts

Fixes an issue where tutorials without a stream were not showing.

FIX: Ensure tutorials with null stream show when stream undefined

---

src/app/projects/states/dashboard/directives/task-dashboard/directives/task-description-card/task-description-card.tpl.html

Show the extensions granted so that the due date is updated.

ENHANCE: Show extension on task details card

---

src/app/units/states/tasks/inbox/inbox.tpl.html

Hotfix for issue with comment panel width

LOOKS: Set max-width of inbox task comment viewer

---

src/app/admin/modals/user-settings-modal/user-settings-modal.tpl.html
src/app/admin/states/users/users.tpl.html
src/app/common/header/header.tpl.html
src/app/common/user-icon/user-icon.component.ts
src/app/tasks/task-comments-viewer/task-comments-viewer.component.html
src/app/units/states/edit/directives/unit-staff-editor/unit-staff-editor.tpl.html
src/app/units/states/students-list/students-list.tpl.html
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.html

Issue was that the email was not linked, but as this is always determined by the user the email property was removed and the email calculated from the user.

Fix issue with user icon in the comment list

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.scss

Stops very small overflow of long names

LOOKS: Truncation adjustment

---

src/app/units/states/edit/directives/unit-details-editor/unit-details-editor.coffee
src/app/units/states/edit/directives/unit-details-editor/unit-details-editor.tpl.html

This PR adds the ability for unit chairs to adjust the setting giving students permission to change tutorials.

ENHANCE: Add option to switch student tutorial change unit setting

---

src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.html
src/app/units/states/tasks/inbox/directives/staff-task-list/staff-task-list.component.scss

Fixes a visual bug with long task descriptions

LOOKS: Fix inbox truncation

---

src/app/doubtfire-angular.module.ts
src/app/doubtfire.states.ts
src/app/home/states/home/home.component.html
src/app/home/states/home/home.component.ts

This adds the start of the new angular home component to replace the
CoffeeScript files & bootstrap styling.
This is the existing component that is being upgraded from Angular.JS to Angular.
Features include:
Fixes # (issue)
- *Please delete options that are not relevant.
- 
- *
*Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration*

refactor: adds new angular home component

---

Dockerfile
package-lock.json
package.json
src/app/common/pipes/marked.pipe.ts
src/app/common/user-icon/user-icon.component.ts
src/app/home/states/home/home.component.html
src/app/home/states/home/home.component.scss
src/app/tasks/task-comments-viewer/task-comments-viewer.component.html

This PR uses node 16 for the web base image.
It also includes various small style and bug fixes.

upgrade node base image version in web dockerfile

---

README.md

docs: add link to CONTRIBUTING.md

---

src/app/projects/states/dashboard/directives/task-dashboard/task-dashboard.coffee
src/app/projects/states/dashboard/directives/task-dashboard/task-dashboard.tpl.html
src/app/tasks/task-comments-viewer/task-assessment-comment/task-assessment-comment.component.html
src/app/tasks/task-submission-history/task-submission-history.component.ts

This PR fixes a few issues with overseer, including reporting errors, style issues causing render problems, and unused components.

fix: improve overseer integration
